### ISSUE TITLE
Received fatal alert: unknown_ca

### ISSUE THREAD

**Issue by jakob-p** [alex-therapeutics/diga-api-client#64]
## Problem

The TLS handshake fails when trying to send a Code Validation Request with this error:

```
javax.net.ssl|ERROR|10|main|2021-12-28 16:13:23.832 CET|TransportContext.java:362|Fatal (UNKNOWN_CA): Received fatal alert: unknown_ca (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: Received fatal alert: unknown_ca
  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:357)
  	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
  	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:203)
  	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
  	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
  	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
  	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
  	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
  	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
  	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
  	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
  	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
  	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
  	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
  	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
  	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
  	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
  	at com.alextherapeutics.diga.implementation.DigaOkHttpClient.post(DigaOkHttpClient.java:69)
  	at com.alextherapeutics.diga.DigaApiClient.performCodeValidation(DigaApiClient.java:225)
  	at com.alextherapeutics.diga.DigaApiClient.sendTestCodeValidationRequest(DigaApiClient.java:152)
```

The keystore was created with the [secon-keystore-generator](https://github.com/mawendo-gmbh/secon-keystore-generator). It worked but displayed this warning:
`Warning: Unable to load 5 certificate(s). `

Any Ideas how to solve this?

**Comment by fongie** [comment]
Hi @jakob-p thanks for opening an issue! In this case, it is likely an issue with your keystore. More specifically, it seems like it could be an issue with your own client certificate - see [this stackoverflow post](https://stackoverflow.com/questions/28958514/javax-net-ssl-sslhandshakeexception-received-fatal-alert-unknown-ca). Did you use the certificate you received from ITSG?

**Comment by jakob-p** [comment]
Hi @fongie Thank you for your quick response and this library!

Yes i used the *.p7c certificate (and its private key) I received from ITSG  together with the annahme-rsa4096.key to generate the keystore

**Comment by fongie** [comment]
No problem! 

I see, I'm afraid I don't have much advice to give. For me one of the most annoying parts of getting all this to work was setting up the certificates. I can only suggest some things which you may have thought about already:

- you could try converting your key into pkcs8 as described [here](https://github.com/mawendo-gmbh/secon-keystore-generator#alternative-private-key-format) before creating the keystore
- you could try to manually send a request using some other tool like `curl` to verify if you indeed have a working certificate/private key. you would need to encrypt an xml body using [secon tool](https://github.com/DieTechniker/secon-tool), which is the process this client does for you. this will be a bit of a hassle but may be worth it if you are really really sure you have the right files
- if you recently received your private key, you could wait a few days to see if perhaps ITSG haven't updated their keystores yet to include your key

I would be inclined to wait a bit and see if it's simply an issue with ITSG not updating their keystores rather than spend a lot of time on debugging this right now if I were you. If it still doesn't work after a few days, I would look into what could have gone wrong with your client certificate.

**Comment by jakob-p** [comment]
I just tested different endpoints, and against the insurance with the key AH i got a 200 OK back for the Test Code Validation 😄   

The other endpoints don't work for me yet. 

Maybe you are right and I need to wait a bit so the other endpoints update their certificates. I got the certificate 8 days ago.

**Comment by fongie** [comment]
Great! I'm happy it started working. It sounds like it will resolve itself after a while, then. I will close this issue if you don't mind. Good luck setting up your diga api integration!

**Comment by kennyx46** [comment]
@jakob-p did eventually work for you? We received our certificate from ITSG 4 days ago and now see "Received fatal alert: handshake_failure" while trying to validate the test code. Interestingly, `AH` insurance key works for us as well.

**Comment by jakob-p** [comment]
The problem was that from December 2021  the ITSG issued certificate from a new root CA and most insurance endpoints did not have this root CA in their systems.

I contacted the insurance endpoints and 7/8 fixed it until now.

For Bitmarck there is a temporary fix using another endpoint. I'm not sure if I can put the URL here, so better contact them if you need the address. But they should have the fix in their official endpoint soon.

**Comment by kennyx46** [comment]
@jakob-p thanks for your answer.
Will try to contact them then.
